[pytest]
# Pytest configuration file

# Test paths
testpaths = tests

# Python files to consider as test modules
python_files = test_*.py

# Python classes to consider as test classes
python_classes = Test*

# Python functions to consider as test functions
python_functions = test_*

# Marker definitions
markers =
    registration: Marks tests related to user registration functionality
    e2e: Marks end-to-end tests
    form_submission: Marks tests related to form submission functionality
    subscription: Marks tests for newsletter subscription scenario
    invalid_login: Marks tests for invalid login scenarios

# Retry + Parallel execution + Reporting configuration
addopts =
    -n 2
    --dist loadscope
    --reruns 2
    --reruns-delay 1
    --alluredir=allure-results
    --html=reports/report.html
    --self-contained-html
    --enable_trace
    
# Log configuration
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

